### PR TITLE
Fix system account frozen field

### LINKED ISSUE #1483: Review and clear accounts that have non-zero`frozen` field
- Why those accounts have non-zero`frozen` field ? [Example](https://darwinia.subscan.io/account/0x7aE2a0914db8bFBdad538b0eAc3Fa473A0e07843)
- Clear if they are not needed anymore.

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Closes #1483.

I'll test Darwinia again once the 6620 runtime upgrade is completed. Do not merge for now.

The algorithm is based on the code found at https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/balances/src/lib.rs#L1028-L1043.

### CODE REVIEW

**Review by hackfisher — APPROVED** [review]

File: runtime/darwinia/src/migration.rs [hunk 1]
```diff
@@ -61,79 +45,42 @@ impl frame_support::traits::OnRuntimeUpgrade for CustomOnRuntimeUpgrade {
...
-	.remove_all();
-
-	let _ = migration::clear_storage_prefix(
-		b"BridgeKusamaGrandpa",
-		b"ImportedHeaders",
-		&[],
-		Some(100),
-		None,
-	);
-
```
Comment (hackfisher) [inline runtime/darwinia/src/migration.rs:136]: This may need to be kept

**Review by hackfisher — CHANGES_REQUESTED** [review]

File: runtime/darwinia/src/migration.rs (hunk 1 above)
Comment (AurevoirXavier) [reply runtime/darwinia/src/migration.rs:136]: 300 keys remaining.

**Review by hackfisher — APPROVED** [review]
